### PR TITLE
FIX: Website URL was leading to a 404

### PR DESCRIPTION
**Pull request by elegantShock2258**
This is in accordance with issue #1

### CODE REVIEW

**Comment by Devnol** [comment]
Oh thank you so much I actually said in my head that I need to add http when I typed it but forgot to actually do it.
Can you please change the protocol to https though?

**Comment by akisblack** [comment]
> Oh thank you so much I actually said in my head that I need to add http when I typed it but forgot to actually do it. Can you please change the protocol to https though?

do it yourself

**Comment by Devnol** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fgfycat.com%2Fgifs%2Fsearch%2Ffine%2Bi%27ll%2Bdo%2Bit%2Bmyself&psig=AOvVaw0EzB73gF4fQJOnZyVF6_8V&ust=1632920983754000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCNj49OzeofMCFQAAAAAdAAAAABAD

**Comment by Devnol** [comment]
https://c.tenor.com/lH6vQ6u5n8AAAAAC/thanos-marvel.gif

**Comment by Devnol** [comment]
Resolved in 6efed42

**Pull request closed without merging**
